### ISSUE TITLE
The sound effect is broken, it seems.

### ISSUE THREAD

**Issue by Lazerbeak12345** [Woldorf/Cursed-Snek#1]
After cloning then installing pygame when it complained after a failed run, it complained that "AppleSound.mp3" is not present. This is on python3.9, pygame 2.0.1

Perhaps adding a `./requirments.txt` file will do the job, make sure I didn't miss any.

**Comment by Woldorf** [comment]
Oh lol I forgot to add the AppleSoung.mp3 file.
