### ISSUE TITLE
The sound effect doesn't seem to be suported or something?

### ISSUE THREAD

**Issue by Lazerbeak12345** [Woldorf/Cursed-Snek#2]
So I pulled the result of issue #1  and the sound effect is there. My system can play it in its default audio player.

But when I run `python3 SNEK.py` it has this error:

```
pygame 2.0.1 (SDL 2.0.14, Python 3.9.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/nate/projects/Cursed-Snek/SNEK.py", line 44, in <module>
    pygame.mixer.music.load("EatingApple.mp3")
pygame.error: Unrecognized audio format
```

**Comment by Woldorf** [comment]
Working on it now, it seems to just be an issue on Linux. When running it on my Windows laptop it works fine but not my Fedora one

**Comment by Woldorf** [comment]
For some reason it glitches when using `.mp3` audio file formats. Fixed by changing the audio format to `.wav`
